version: "1"
services:
  server:
    environment:
      TAG: movie
    build: .
    container_name: movie
    restart: on-failure
    ports:
      - "8080:8080"
    env_file:
      - .env

networks:
  default:
    external: true
    name: movie